
<!-- Para renderizar: bookdown::render_book("index.Rmd", "bookdown::pdf_book") -->

# Resumen / Summary

\noindent 
En los modelos de predicción genómica convencionales se utilizan solo los individuos con genotipo. El método del mejor predictor lineal insesgado genómico de un solo paso (ssGBLUP) permite integrar individuos genotipados y no genotipados, siempre que estén conectados por un pedigrí. El objetivo de este estudio consistió en evaluar la utilidad de esta metodología de selección en la predicción genómica del arroz. Se usaron datos del tiempo de floración de 451 individuos de arroz de la variedad Indica genotipada con 100.231 SNP. Debido a la falta del pedigrí, se llevó a cabo simulaciones de dos tipos, hacia atrás (ancestral) y hacia adelante (descendientes). En la simulación ancestral, se usó el software Molcoanc para crear antepasados virtuales a partir de los 451 individuos genotipados. En la simulación de descendientes, se empleó el paquete de Python SeqBreed para generar descendencia de esos 451 individuos, repartidos en distintas generaciones (F1, F2 y F3). Se evaluaron distintos escenarios de densidad de marcadores (ninguno, 1.000, 10.000 y 100.000) y de individuos genotipados según el tipo de simulación: (i) simulación ancestral con ninguno, 148, 298 y 451 individuos genotipados, y (ii) simulación de descendientes con ningún individuo, solo la generación F2, la generación F2 y F3, y todos los individuos genotipados. Se usó el coeficiente de correlación entre los valores fenotípicos observados y predichos como medida de predictibilidad. Los resultados revelaron que, en ambos tipos de simulación, la precisión de la predicción mediante el ssGBLUP tiende a mejorar comparado con el mejor predictor lineal insesgado convencional (BLUP) que utiliza únicamente la información del pedigrí. En la simulación ancestral se observaron ganancias esperadas en la precisión por encima del 1.0% con respecto al BLUP (al considerar una densidad del marcador de 10.000 en 298 individuos genotipados) y entre el 13% al 18% (al considerar una densidad del marcador de 10.000 en 451 individuos genotipados). En cuanto a la simulación de descendientes, también se pudo observar precisiones más altas al realizar la predicción mediante el ssGBLUP. Los análisis sugieren utilizar una cantidad de marcadores entre 1.000 y 10.000 para obtener una precisión equivalente a usar todos los marcadores disponibles. Por lo tanto, el uso combinado de la información genómica y del pedigrí mediante el método ssGBLUP puede ser un enfoque interesante para aumentar la precisión de la predicción en los programas de mejora genética en los cultivos de arroz.

\hspace*{1em}
\noindent 
__Palabras clave:__ matriz de parentesco, parámetros genéticos, precisión de la predicción, predicción genómica.

---

\noindent 
In traditional genomic prediction models, only individuals with the genotype are used. The single-step genomic best linear unbiased predictor (ssGBLUP) method allows integrating genotyped and non-genotyped individuals, provided they are connected by a pedigree. The objective of this study was to evaluate the use of this selection methodology in the genomic prediction of rice. Flowering time data from 451 Indica rice individuals genotyped with 100.231 SNPs were used. Due to the absence of the pedigree, two types of simulations were carried out, backwards (ancestor) and forwards (offspring). In the ancestry simulation, Molcoanc software was used to create virtual ancestors from the 451 genotyped individuals. In the offspring simulation, the SeqBreed Python package was used to generate offspring from these 451 individuals, divided into different generations (F1, F2 and F3). Different marker density (none, 1.000, 10.000 and 100.000) and genotyped individuals scenarios were evaluated according to the type of simulation: (i) ancestors simulation with none, 148, 298 and 451 individuals genotyped, and (ii) offspring simulation with none individuals, only F2 generation, the F2 and F3 generation, and all the individuals genotyped. The correlation coefficient between the observed and predicted phenotypic values was used as a measure of predictive ability. The results revealed that in both types of simulation, the prediction accuracy using the ssGBLUP is better compared to the conventional best linear unbiased prediction (BLUP) that uses only the pedigree information. In the ancestors simulation, expected gains in precision were observed above 1.0% with respect to the BLUP (considering a marker density of 10.000 in 298 genotyped individuals) and between 13% and 18% (considering a marker density of 10.000 in 451 genotyped individuals). In the offspring simulation, higher precisions were also observed when making the prediction using ssGBLUP. The analyzes suggest using a number of markers between 1.000 and 10.000, to obtain an accuracy equivalent to using all available markers. Therefore, the combined use of genomic and pedigree information in the ssGBLUP method may be an interesting approach to improvement prediction accuracy in rice breeding programs.

\hspace*{1em}
\noindent 
__Key words:__ relationship matrix, genetic parameters, prediction accuracy, genomic prediction.

\newpage
