
<!-- Para renderizar: bookdown::render_book("index.Rmd", "bookdown::pdf_book") -->

# Discusión



<!--

- single-step BLUP with varying...

pag 936 (mejor stimación de par. gene.) y 937 (0 ind. genotipados implica el análisis mediante BLUP con la matriz A).

--

- single-step genomic prediction of fruit-quality...

pag 8 a la 10, para guiarme en constuir mi discusión.

--

- Genomic selection: a breakthrough ...

pag 669 (la GS en arroz se ha probado recientemente), pag 670 (la GS se puede usar en arroz y estudios muestra viabilidad de la GS en arroz... recordar aquí el parrafo que el profesor Miguel me dijo que quitara o colocara en otra parte acerca de la simulacion en arroz), pag 671 (ejemplos de estudios de GS en arroz) y pag 672 (hay pocos estudios de GS en arroz).

--

- single-step reaction norm models ...

pag 594 (el ssGBLUP es escaso en plantas)

--

- Will genomic selection ...

pag 1304 (en el fitomejoramiento la GS no es popular aún) y pag 1306 (los estudios de GS son más comunes en animales que en plantas por varios motivos)

- Single-step genomic and pedigree genotype x environment ...

pag 2 (la GS se esta convirtiendo en un enfoque estándar para lograr progreso genético en plantas), pag 3 (el ssGBLUP no se ha aplicado ampliamente en el fitomejoramiento), pag 13 (la matriz H como solución a la no pisbilidad de usar la GS en trigo), pag 13 (el ssGBLUP es atractivo en plantas) y pag 14 (la matriz H implica muchas cosas)

--

- Assesing prediction models ...

pag 1 (los programas de mejora genética en arroz garantizaran la seguridad alimentaria), pag 6 (mejor precisión del ssGLUP y GBLUP que de ABLUP), pag 7 (el LD es la base de la GS... si quisiera incluir el LD, en este articulo a partir de la pagina 6 explican muchas cosas relacionadas con el LD) y pag 11 (con datos genómicos es mayor la precisión, y ejemplos de estudio donde se evidencia esto)

--

- Effect of hidden relatedness on single-step ...

pag 4 (el genotipado completo de arboles forestlaes no es factible), pag 12 (precisión ligeramente mayor en ssGBLUP que en ABLUP) y pag 13 (matriz de relaciones realizada permite mejor estimación de los parámetros genéticos)

--

- The impact of genotyping different groups ...

pag 5415 (ejemplo de un objetivo dentro de la discusión)

--

- increasing accuracy and reducing costs ...

pag 5 (pequeños subconjunto de marcadores inducen una disminución en la varianza residual), pag 18 (cuando se usan todos los marcadores, se encontraron los valores más altos de las varianzas residuales), pag 18 (baja densidad de marcadores es deseable para reducir los costos de genotipado), pag 11 (estudio hecho en arroz (creación de arreglos de SNP 6 k) con SNP representativos seleccionados) y pag 18 (los resultados del estudio evidencian que es posible seleccionar los marcadores y construir matriz de bajo costo para implementar la GS... hay varias frases en esta pagina donde indican la construcción de estas matrices)

--

- Genomic selection and association mapping ...

pag 12 (la GS permite reducir el ciclo de mejoramiento en arroz y aumentar el progreso genético)

--

- genomic selection methods for crop improvement:...

pag 337 (El deterioro de las relaciones puede afectar la precisión) y pag 337 (es mejor volver a estimar los efectos del marcador o del haplotipo cada 2 o 3 generaciones)

-- genomic selection: genome-wide...

pag 593 (la GS se ha practica en animales pero poco en plantas) y pag 598 (la ausencia de LD entre el marcador y el QTL reduce la precisión)

--

- Genomic selection in rice: ...

pag 244 (para que la GS se use en la mejoar de plantas se debe considerar la interacción G x E)

--

- Genomic prediction: progress and ...

pag 5 (la implementación de la GS en arroz se ha retrasado en relación con los animales), pag 6 (interés en la implementación de la GS en arroz), pag 7 (los estudios de GS en arroz se comenzaron a publicar apenas en el 2014), pag 9 y pag 13 (el GBLUP es el método de GS de referencia debido a su simplicidad), pag 18 (con la GS se reduce el tiempo de mejora), pag 18 (métodos que se pueden implementar en compañia de la GS) y pag 24 (despues de identicar los factores que afectan la GS, el costo es limitante)

--

- Genomic selection in cereal breeding

pag 2 (la gs es prometedora en plantas), pag 2 y 8 (se ha ignorado el pedigrí en plantas) y pag 11 (la mejora genética en plantas podría beneficiarse de la información de pedigrí y de la información molecular).

-->

Los análisis genéticos cuantitativos se han basado tradicionalmente en la metodología de los modelos mixtos. Desde el desarrollo de esta metodología, el progreso genético logrado en los programas de mejora genética ha sido en gran parte al uso del pedigrí [@cite:30], y a la matriz A que se obtiene a partir de este tipo información. La matriz A se ha utilizado ampliamente para estimar el parentesco <!--(o covarianza genética)--> entre individuos a través del BLUP. Sin embargo, en los últimos años, se han propuesto estimadores del parentesco distintos al basado en el pedigrí, ya que en este último se asume una relación promedio entre individuos fundadores igual a cero [@cite:71], además de que se ignora el término de muestreo Mendeliano [@cite:72]. <!--Por otro lado, a pesar del interés que en su momento hubo en el uso del pedigrí para la mejora genética de animales, el uso de este tipo de información en plantas no fue relevante [@cite:63].--> Al proponer los métodos de selección genómica [@cite:8], y con el posterior desarrollo del GBLUP en el que se utiliza la matriz G con información de genotipos en lugar de la matriz A [@cite:39], fue posible solucionar las desventajas anteriormente mencionadas del BLUP, debido a que los métodos de selección genómica basados en información de genotipos tienen en cuenta la variación genética no explicada por el pedigrí debido a la variación del muestreo Mendeliano [@cite:40; @cite:69], además de que revelan relaciones entre individuos que aparentemente no están relacionados en el pedigrí [@cite:74].

<!--A partir del estudio de @cite:73, en el que se propuso incorporar información de genotipos en el BLUP, @cite:8 plantearon los métodos de selección genómica. Siguiendo las consideraciones precedentes, @cite:39 desarrollo el GBLUP, el cual es un método de selección genómica que consiste en resolver un modelo mixto utilizando la matriz G en lugar de la matriz A. En relación con lo anterior, algunos estudios han informado la superioridad de los métodos de selección genómica sobre el BLUP en animales [@cite:75] y en plantas [@cite:68; @cite:20; @cite:11]. Esto último debido a que los métodos de selección genómica basados en información de genotipos tienen en cuenta la variación genética no explicada por el pedigrí debido a la variación del muestreo Mendeliano [@cite:40; @cite:69], además de que revelan relaciones entre individuos que aparentemente no están relacionados en el pedigrí [@cite:74].--><!-- Se ha demostrado también el uso potencial de los métodos de selección genómica para la mejora genética de los cultivos de arroz a través de estudios de simulación [@cite:60].-->

Sin embargo, el costo para obtener un genotipado completo de individuos puede ser una limitante en el uso de los métodos anteriormente mencionados de selección genómica<!--[@cite:19; @cite:72; @cite:76], además que para su implementación se recomienda utilizar información de individuos sin genotipo y con genotipo en el mismo análisis de datos como forma de eliminar el sesgo asociado con la dependencia en el uso de individuos genotipados [@cite:72]-->. Como solución a estos problemas se propuso el desarrollo del ssGBLUP, el cual es un método de selección donde la información genómica se extiende a los individuos sin genotipo a partir de una matriz de parentesco combinada con información de genotipos y del pedigrí [@cite:17; @cite:16], denominada como matriz H. En vista a esto, consideramos que la selección genómica mediante el ssGBLUP puede ser una opción interesante para la mejora genética en el arroz, debido a que permite obtener (de manera rentable) predicciones más precisas a través de una mejor estimación del parentesco entre individuos<!--, y también estimaciones más precisas de los parámetros genéticos-->.

La heredabilidad en sentido estricto, definida como la relación entre la varianza genética aditiva y la varianza fenotípica, es un parámetro central en la genética cuantitativa debido a que cuantifica qué parte de la variación fenotípica en el carácter es causada por factores genéticos, y proporciona una referencia para planificar esquemas de mejora genética. <!--Hasta donde sabemos, la heredabilidad de caracteres de relevancia económica en arroz no llego a ser estimada de forma tradicional mediante el uso de información de pedigrí, debido a que el uso de este tipo de información no era relevante [@cite:63].--> El valor de la estima de heredabilidad para el carácter tiempo de floración en este estudio, se ubicó en los rangos informados en otros estudios como el de @cite:68 con valores entre 0.81 a 0.89, y el de @cite:69 con valores de 0.83 a 0.99, valores que indican que se trata de un carácter muy heredable. De acuerdo con @cite:26, el tiempo de floración es un carácter particularmente importante, debido a que tiene un impacto económico en la producción de arroz. A partir de los resultados obtenidos en este estudio, podemos afirmar que el número de marcadores y de individuos genotipados pudieron afectar la precisión con que se estimó la heredabilidad para el carácter tiempo de floración.

El factor más importante que determina el éxito de la selección genómica es la predicción precisa del GEBV [@cite:6]. <!--Según @cite:69, la evaluación de la precisión se considera un requisito previo que permite comprender el potencial de un conjunto de datos para la predicción genómica. -->En el tiempo actual, se ha logrado grandes avances en la comprensión de los principales factores que afectan la precisión del GEBV, entre ellos el número de marcadores y de individuos genotipados [@cite:6; @cite:10; @cite:68; @cite:58]. En relación con el número de marcadores, de acuerdo con @cite:31 e @cite:20, la precisión de la predicción es más baja con un número insuficiente de marcadores debido a que la probabilidad de asociación (o desequilibrio de ligamiento) entre dichos marcadores con el QTL tiende a disminuir. Sin embargo, aunque la teoría indica que a mayor cantidad de marcadores mejor será la predicción, se ha demostrado también que a ciertas densidades es difícil mejorar significativamente dicha precisión [@cite:77].

Esto último se observó en los resultados obtenidos en nuestro estudio (Figuras 5.4 y 5.5), ya que al utilizar una densidad aproximada entre 1.000 y 10.000 marcadores se evidenció una precisión similar a usar la mayor cantidad de marcadores disponibles. A este respecto, varios estudios han evaluado la posibilidad de usar menos cantidad de marcadores sin afectar notablemente la precisión de la predicción genómica. A partir de una población constituida por 369 líneas de arroz mejorado del Instituto Internacional de Investigación del Arroz (IRRI), @cite:32 determinaron el número de marcadores necesario para implementar la selección genómica, seleccionando de forma aleatoria y distribuidos uniformemente en todo el genoma subconjuntos de los 73.147 marcadores disponibles, observando para casi todos los caracteres evaluados diferencias no significativas en la precisión de la predicción genómica con una cantidad mayor a 7.142 marcadores. @cite:83 investigaron el efecto de la densidad de marcadores en la predicción genómica de caracteres de crecimiento en bovino de carne Simmental Chino, estudio que demostró que la precisión para la selección genómica puede alcanzar una meseta a densidades bajas de marcadores. En un estudio llevado a cabo para caracteres de crecimiento en camarón blanco del Pacífico, @cite:82 reportaron una mejora en la precisión de la predicción con un aumento en el número de marcadores, evidenciando también un efecto débil de la densidad del marcador sobre dicha precisión después de que la cantidad de marcadores alcanzara un valor de 3.200. Una tendencia similar se encuentra en otros estudios [@cite:79; @cite:81; @cite:78; @cite:84; @cite:80] donde se menciona que si la densidad del marcador alcanza cierto nivel, ya no es beneficioso para la precisión de la predicción genómica.

<!--Como consecuencia de lo anterior, durante los últimos años se han propuesto diferentes metodologías que permiten identificar y seleccionar subconjuntos de marcadores con asociación directa con el QTL. @cite:85, sugirieron el uso de tres métodos de aprendizaje automático (Random Forests, Gradient Boosting Machine y Extreme Gradient Method) en la identificación de subconjuntos de marcadores para la predicción genómica. Utilizando información de 38.082 marcadores y del fenotipo peso corporal en bovinos Brahman, estos autores demostraron que los métodos de aprendizaje automático eran métodos eficientes para identificar subconjuntos de SNP con asociación directa a genes que pueden afectar dicho carácter de crecimiento, demostrando también que la precisión de la predicción genómica a partir de los 3.000 marcadores identificados utilizando estos métodos era similar a la precisión obtenida en base al total de 38.082 marcadores. En otros estudios [@cite:86; @cite:84] se ha mencionado también los beneficios de identificar y seleccionar subconjuntos de marcadores para reducir el costo del genotipado mientras se mantiene la capacidad predictiva a un nivel razonable.--><!-- NOTA: la eliminación de los marcadores que presentan un efecto pequeño es una buena estrategia que tiene el potencial de construir un chip SNP de baja densidad específico del rasgo y reducir los costos de genotipado en los programas de mejoramiento. Es posible seleccionar los marcadores más informativos para mejorar la precisión y construir una matriz de bajo costo para implementar la selección genómica en programas de mejoramiento basados en un panel de alta densidad. -->

De acuerdo a @cite:77, la predicción genómica es más precisa a mayor cantidad de individuos genotipados (o en conjuntos de entrenamiento más grandes) debido a que cuanto mayor es la cantidad de individuos genotipados, más muestras con información de fenotipos y de genotipos se pueden utilizar, y en consecuencia, la precisión de la estimación de los efectos genéticos se puede mejorar. Nuestros resultados (Figuras 5.4 y 5.5), así como los obtenidos en otros estudios [@cite:87; @cite:72; @cite:88], respaldan esta afirmación a través de una mejora en la precisión de la predicción al aumentar la cantidad de individuos genotipados. A diferencia del estudio en trigo harinero llevado a cabo por @cite:78, quienes informaron de una precisión en la predicción máxima entre 3.930 y 7.450 individuos genotipados, en nuestro estudio no se evidenció un punto en el que dicha precisión tendiera a estabilizarse. Los mismos autores [@cite:78] señalan lo difícil que es determinar el tamaño del conjunto de entrenamiento ideal, debido a que el número de individuos genotipados necesarios para ubicar un punto de rendimiento decreciente suele tener un costo prohibitivamente alto.

En relación a lo anteriormente mencionado, @cite:58 y @cite:88 afirman que en los programas de mejora genética (tanto en plantas y como en animales), no siempre son posibles grandes conjuntos de entrenamiento, y una forma de resolver este problema consiste en diseñar estrategias de genotipado para optimizar la composición de un conjunto de entrenamiento con el que se pueda lograr una buena precisión en la predicción.




<!--
**Sin embargo, los grandes conjuntos de entrenamiento no siempre son factibles debido principalmente a los costos de genotipado y fenotipado. Se desarrollaron varios métodos para optimizar la composición del conjunto de entrenamiento con el fin de lograr altas precisiones mientras se mantiene el tamaño en un número manejable [39, 42, 46, 69, 73, 78, 127–129].


**El tamaño y las características de la población genotipada dependen de la especie y del programa de reproducción, y su composición juega un papel importante en la precisión de la predicción. Las ganancias en la precisión de la predicción y los tamaños de población genotipados están fuertemente relacionados ( Daetwyler et al., 2012 ; Auvray et al., 2014 ; Schöpke y Swalve, 2016).). Sin embargo, los programas de mejoramiento suelen tener recursos económicos limitados para el genotipado, lo que hace que la decisión de seleccionar candidatos sea mucho más cautelosa. Para resolver este problema común, una gran cantidad de investigación se centra en el diseño de estrategias de genotipado para optimizar la selección de individuos a genotipificar
-->

<!--
Las características de la TP que afectan la PA de las predicciones genómicas incluyen su tamaño, su estructura y su relación con la CP. En los experimentos de predicción basados en validación cruzada que revisamos, el tamaño del TP fue de alrededor de cuatro quintos del número total de entradas disponibles, que varió de 110 a 575. El tamaño resultante del TP fue muy inferior el valor teórico de 1500 para un Ne de 50. De hecho, como informan Grenier et al. (2015), el Ne superior a 50 se puede observar en una población de base genética bastante limitada. Estos pequeños tamaños de la TP son probablemente una de las causas de la baja PA de predicción genómica observada en todos los estudios, incluso para rasgos fenotípicos de alta heredabilidad, como los días a floración (Cuadro 15.1). 

--

Varios estudios han demostrado que la precisión de las predicciones está influenciada por el tamaño de la población de entrenamiento. Es muy importante que los mejoradores determinen el número de líneas que se van a genotipar y fenotipar para establecer un conjunto de datos de entrenamiento adecuado, porque la configuración de los primeros datos de entrenamiento suele ser una gran inversión. En un estudio de cebada de primavera, Nielsen et al. [18] observaron una precisión reducida de GS como resultado de la reducción del conjunto de datos de entrenamiento y, además, las precisiones parecían menos estables con rondas de CV que mostraban una mayor variación en la precisión para un conjunto de datos de entrenamiento pequeño. Cericola et al. [19] encontró un aumento en la precisión de la predicción con el aumento del tamaño de la población de entrenamiento, alcanzando una meseta en ~ 700 líneas que consisten en líneas de trigo de hermanos completos, medios hermanos y menos relacionadas de 3 ciclos de mejoramiento consecutivos. Sin embargo, se encontró que el tamaño óptimo del conjunto de entrenamiento era mayor en un estudio realizado por Norman et al. [20] utilizando tamaños de conjuntos de entrenamiento que varían de 250 a 8300 líneas con diferentes relaciones. Meuwissen [21] también observó un aumento en la precisión de la predicción como resultado del aumento del tamaño de la población de entrenamiento utilizando individuos relacionados de forma lejana.

--

**Por lo general, un gran conjunto de entrenamiento puede mejorar la precisión de la predicción, porque cuanto mayor sea el conjunto de entrenamiento, más muestras con información fenotípica y genotípica se pueden utilizar y, por lo tanto, la precisión de la estimación de los efectos genéticos se puede mejorar en consecuencia [ 5 ], especialmente para rasgos con baja heredabilidad [ 74 ]

--

En general, a medida que aumenta el tamaño de la muestra, la precisión de la predicción aumenta, aunque es fundamental considerar otros factores que influyen. Un aumento en el TP de una población de trigo biparental (TP que comprende 96, 48 y 96) [19] y un programa de mejoramiento de trigo multifamiliar (TP que comprende 96, 192 y 256) [20] resultó en un aumento en el precisión de la predicción.

--

Una vez que se ha definido el punto de entrada de la predicción genómica en el esquema de mejoramiento, el diseño del conjunto de entrenamiento es el primer paso hacia la implementación de la selección genómica. Se deben hacer tres elecciones principales con respecto al conjunto de entrenamiento: su composición y tamaño, su fenotipado y su genotipado. El criador debe encontrar un equilibrio entre estos tres aspectos para optimizar el conjunto de entrenamiento de acuerdo con los recursos disponibles. Una forma sencilla para que la mayoría de los programas de mejoramiento comiencen es comenzar a genotipificar cada línea que ingresa a la prueba de rendimiento. A partir de ahí, esos conjuntos de datos se pueden optimizar empíricamente para aumentar la precisión de la predicción.

**Es bien sabido que la precisión aumenta con el tamaño del conjunto de entrenamiento. Los estudios teóricos [122-124] y empíricos [65, 125, 126] sugieren que el tamaño del conjunto de entrenamiento debe maximizarse cuando se trata de rasgos complejos. Sin embargo, los grandes conjuntos de entrenamiento no siempre son factibles debido principalmente a los costos de genotipado y fenotipado. Se desarrollaron varios métodos para optimizar la composición del conjunto de entrenamiento con el fin de lograr altas precisiones mientras se mantiene el tamaño en un número manejable [39, 42, 46, 69, 73, 78, 127–129]. Todos estos métodos utilizan las relaciones genéticas aditivas (generalmente basadas en datos de marcadores) para muestrear de manera óptima un conjunto de genotipos representativos. Un aspecto clave de la optimización del conjunto de entrenamiento es la definición del conjunto predicho (candidatos de selección). De hecho, las estrechas relaciones genéticas entre el conjunto de entrenamiento y los candidatos de selección son clave para maximizar la precisión de la predicción [130, 131]. Por lo tanto, la mayoría de los métodos de optimización están considerando conjuntamente los genotipos que compondrán el entrenamiento y los conjuntos pronosticados para calcular directamente los criterios basados en la relación (el promedio de los coeficientes de relación entre el conjunto de entrenamiento y el conjunto pronosticado [128, 132]) o para estimar criterios basados en la teoría de modelos mixtos (la varianza del error de predicción, el coeficiente de determinación o la precisión esperada [39, 78, 127]). En los casos en que el entrenamiento y los conjuntos pronosticados provienen de la misma población (p. ej., candidatos de selección de la misma cohorte) o la información sobre los individuos predichos aún no está disponible (p. ej., descendencia), se han desarrollado métodos de optimización para minimizar las relaciones genéticas. entre individuos del conjunto de entrenamiento [46, 73]. Dependiendo de la disponibilidad de datos y los objetivos de predicción, el criador puede elegir entre estos métodos de optimización para dar forma al conjunto de entrenamiento y actualizarlo cuando sea necesario predecir candidatos de selección de un nuevo ciclo.
-->
