```{r, echo = FALSE}

pacman::p_load(tibble, gt, dplyr, tidyr)
```

<!-- Para renderizar: bookdown::render_book("index.Rmd", "bookdown::pdf_book") -->

# (APPENDIX) Appendix {-}

# Anexos

## Función para el calculo de la matriz de parentesco combinada

```{r, echo = TRUE, eval = FALSE}

fn.mH <- function(ped, mG) { # Esta función recibe como argu-
                             # mentos los datos con estructu- 
                             # ra (id | sire | dam | Gen (TRUE 
                             # /FALSE)) y la matriz de relacio-
                             # nes genómicas.
  
  # 1. Se calcula la matriz de relaciones aditivas con base en 
  # el pedigrí (A)
  
  ped_edit <- pedigreemm::editPed( # Esta función ordena el pe-
                                   # digrí.
    sire = ped$sire,
    dam = ped$dam,
    label = ped$id
    )
  pedi <- pedigreemm::pedigree( # Aquí se usa la salida anterior
                                # (ya ordenado) y se crea un ob-
                                # jeto de clase pedigree.
    sire = ped_edit$sire,
    dam = ped_edit$dam,
    label = ped_edit$label
    )
  Matrix_A <- pedigreemm::getA(ped = pedi) # Esto dara la matriz
                                           # de relaciones adi-
                                           # tivas A.
 
  # 2. De lo anterior (Matriz_A) se extraen las partes correspon-
  # dientes a individuos no genotipados (1) y genotipados (2)
  
  # Individuos no genotipados:
  A_11 <- Matrix_A[ped$Genotiped != 1, ped$Genotiped != 1]
  # Individuos genotipados:
  A_22 <- Matrix_A[ped$Genotiped == 1, ped$Genotiped == 1]
  # Individuos no genotipados (en filas) y genotipados (en 
  # columnas):
  A_12 <- Matrix_A[ped$Genotiped != 1, ped$Genotiped == 1]
  # Transpuesta de la anterior (individuos no genotipados en 
  # columnas y genotipados en filas):
  A_21 <- t(A_12)
  
  # 3. Se coloca el nombre de las filas y y de las columnas 
  # de la matriz G según los individuos genotipados
  
  rownames(mG) <- ped$id[ped$Genotiped == 1]
  colnames(mG) <- ped$id[ped$Genotiped == 1]
  
  # 4. Teniendo todos los componentes de la matriz H, se pro-
  # cede a su construcción
  
  H_11 <- A_11 - 
    (A_12 %*% solve(A_22) %*% A_21) + 
    (A_12 %*% solve(A_22) %*% mG %*% solve(A_22) %*% A_21)
  H_12 <- A_12 %*% solve(A_22) %*% mG
  H_21 <- t(H_12)
  H_22 <- mG
  
  H_11_H_12 <- cbind(H_11, H_12)
  H_21_H_22 <- cbind(H_21, H_22)
  mH <- rbind(H_11_H_12, H_21_H_22)
  
  mH <- mH[order(as.numeric(rownames(mH))), 
           order(as.numeric(colnames(mH)))]
  mH <- Matrix(mH)
  
  # 5. Finalmente se indica retornar la matriz H (mH)
  
  return(mH)
  }
```

## Habilidad predictiva

```{r, echo = FALSE, out.width = "100%", fig.align = 'center', message = FALSE}

Cor_ped_1_est <- read_delim(here('figures', 'Ped1_Bay_Pen.txt'), delim = '\t') %>%
  mutate(
    Densidad = case_when(
      Densidad == 0 ~ '0',
      Densidad == 1 ~ '1.000',
      Densidad == 10 ~ '10.000',
      Densidad == 100 ~ '100.000'
      ),
    Genotipados = as.factor(Genotipados),
    Pedigrí = 'Pedigrí 1'
    )

Cor_ped_2_est <- read_delim(here('figures', 'Ped2_Bay_Pen.txt'), delim = '\t') %>%
  mutate(
    Densidad = case_when(
      Densidad == 0 ~ '0',
      Densidad == 1 ~ '1.000',
      Densidad == 10 ~ '10.000',
      Densidad == 100 ~ '100.000'
      ),
    Genotipados = as.factor(Genotipados),
    Pedigrí = 'Pedigrí 2'
    )

Cor_ped_3_est <- read_delim(here('figures', 'Ped3_Bay_Pen.txt'), delim = '\t') %>%
  mutate(
    Densidad = case_when(
      Densidad == 0 ~ '0',
      Densidad == 1 ~ '1.000',
      Densidad == 10 ~ '10.000',
      Densidad == 100 ~ '100.000'
      ),
    Genotipados = as.factor(Genotipados),
    Pedigrí = 'Pedigrí 3'
    )

Cor_ped <- bind_rows(Cor_ped_1_est, Cor_ped_2_est, Cor_ped_3_est)

Cor_ped %>%
  filter(Pedigrí == 'Pedigrí 1') %>%
  pivot_wider(names_from = Enfoque, values_from = c(Correlación, des)) %>%
  relocate(des_Bayesiano, .before = Correlación_Penalizado) %>%
  select(Genotipados, Correlación_Bayesiano, des_Bayesiano, Correlación_Penalizado, des_Penalizado) %>%
  gt() %>%
  tab_header(
    title = 'Pedirí 1',
    subtitle = '751 individuos en total'
  ) %>%
  cols_label(
    Correlación_Bayesiano = 'Media',
    des_Bayesiano = 'Desvío',
    Correlación_Penalizado = 'Media',
    des_Penalizado = 'Desvíó'
  ) %>%
  tab_row_group(
    label = 'Densidad 100.000',
    rows = 8:10
    )  %>%
  tab_row_group(
    label = 'Densidad 10.000',
    rows = 5:7
    ) %>%
  tab_row_group(
    label = 'Densidad 1.000',
    rows = 2:4
    ) %>%
  tab_row_group(
    label = 'Densidad 0',
    rows = 1
    ) %>%
  tab_spanner(
    label = 'Bayesiano',
    columns = c(2, 3)
  ) %>%
  tab_spanner(
    label = 'Penalizado',
    columns = c(4, 5)
  )

Cor_ped %>%
  filter(Pedigrí == 'Pedigrí 2') %>%
  pivot_wider(names_from = Enfoque, values_from = c(Correlación, des)) %>%
  relocate(des_Bayesiano, .before = Correlación_Penalizado) %>%
  select(Genotipados, Correlación_Bayesiano, des_Bayesiano, Correlación_Penalizado, des_Penalizado) %>%
  gt() %>%
  tab_header(
    title = 'Pedirí 2',
    subtitle = '1661 individuos en total'
  ) %>%
  cols_label(
    Correlación_Bayesiano = 'Media',
    des_Bayesiano = 'Desvío',
    Correlación_Penalizado = 'Media',
    des_Penalizado = 'Desvíó'
  ) %>%
  tab_row_group(
    label = 'Densidad 100.000',
    rows = 8:10
    )  %>%
  tab_row_group(
    label = 'Densidad 10.000',
    rows = 5:7
    ) %>%
  tab_row_group(
    label = 'Densidad 1.000',
    rows = 2:4
    ) %>%
  tab_row_group(
    label = 'Densidad 0',
    rows = 1
    ) %>%
  tab_spanner(
    label = 'Bayesiano',
    columns = c(2, 3)
  ) %>%
  tab_spanner(
    label = 'Penalizado',
    columns = c(4, 5)
  )

Cor_ped %>%
  filter(Pedigrí == 'Pedigrí 3') %>%
  pivot_wider(names_from = Enfoque, values_from = c(Correlación, des)) %>%
  relocate(des_Bayesiano, .before = Correlación_Penalizado) %>%
  select(Genotipados, Correlación_Bayesiano, des_Bayesiano, Correlación_Penalizado, des_Penalizado) %>%
  gt() %>%
  tab_header(
    title = 'Pedirí 3',
    subtitle = '2451 individuos en total'
  ) %>%
  cols_label(
    Correlación_Bayesiano = 'Media',
    des_Bayesiano = 'Desvío',
    Correlación_Penalizado = 'Media',
    des_Penalizado = 'Desvíó'
  ) %>%
  tab_row_group(
    label = 'Densidad 100.000',
    rows = 8:10
    )  %>%
  tab_row_group(
    label = 'Densidad 10.000',
    rows = 5:7
    ) %>%
  tab_row_group(
    label = 'Densidad 1.000',
    rows = 2:4
    ) %>%
  tab_row_group(
    label = 'Densidad 0',
    rows = 1
    ) %>%
  tab_spanner(
    label = 'Bayesiano',
    columns = c(2, 3)
  ) %>%
  tab_spanner(
    label = 'Penalizado',
    columns = c(4, 5)
  )
```

## Habilidad predictiva

```{r, echo = FALSE, out.width = "100%", fig.align = 'center', message = FALSE}

Cor_F2_est <- read_delim(here('figures', 'Ped_F2.txt'), delim = '\t') %>%
  mutate(
    Densidad = case_when(
      Densidad == 0 ~ '0',
      Densidad == 1 ~ '1.000',
      Densidad == 10 ~ '10.000',
      Densidad == 100 ~ '100.000'
      ),
    Predicción = 'F2',
    Pedigrí = case_when(
      Pedigrí == 'Pedigrí_1' ~ 'Pedigrí 1',
      Pedigrí == 'Pedigrí_2' ~ 'Pedigrí 2',
      Pedigrí == 'Pedigrí_3' ~ 'Pedigrí 3',
      Pedigrí == 'Pedigrí_4' ~ 'Pedigrí 4'
      )
    )

Cor_F3_est <- read_delim(here('figures', 'Ped_F3.txt'), delim = '\t') %>%
  mutate(
    Densidad = case_when(
      Densidad == 0 ~ '0',
      Densidad == 1 ~ '1.000',
      Densidad == 10 ~ '10.000',
      Densidad == 100 ~ '100.000'
      ),
    Predicción = 'F3',
    Pedigrí = case_when(
      Pedigrí == 'Pedigrí_1' ~ 'Pedigrí 1',
      Pedigrí == 'Pedigrí_2' ~ 'Pedigrí 2',
      Pedigrí == 'Pedigrí_3' ~ 'Pedigrí 3',
      Pedigrí == 'Pedigrí_4' ~ 'Pedigrí 4'
      )
  )

Cor_F2_F3 <- bind_rows(Cor_F2_est, Cor_F3_est)

Cor_F2_F3 %>%
  filter(Pedigrí == 'Pedigrí 1') %>%
  pivot_wider(names_from = Predicción, values_from = c(Media, Desvio)) %>%
  relocate(Desvio_F2, .after = Media_F2) %>%
  select(Genotipados, Media_F2, Desvio_F2, Media_F3, Desvio_F3) %>%
  gt() %>%
  tab_header(
    title = 'Pedirí 1',
    subtitle = '2061 individuos en total'
  ) %>%
  cols_label(
    Media_F2 = 'Media',
    Desvio_F2 = 'Desvío',
    Media_F3 = 'Media',
    Desvio_F3 = 'Desvío'
  ) %>%
  tab_row_group(
    label = 'Densidad 100.000',
    rows = 8:10
    )  %>%
  tab_row_group(
    label = 'Densidad 10.000',
    rows = 5:7
    ) %>%
  tab_row_group(
    label = 'Densidad 1.000',
    rows = 2:4
    ) %>%
  tab_row_group(
    label = 'Densidad 0',
    rows = 1
    ) %>%
  tab_spanner(
    label = 'F2',
    columns = c(2, 3)
  ) %>%
  tab_spanner(
    label = 'F3',
    columns = c(4, 5)
  )

Cor_F2_F3 %>%
  filter(Pedigrí == 'Pedigrí 2') %>%
  pivot_wider(names_from = Predicción, values_from = c(Media, Desvio)) %>%
  relocate(Desvio_F2, .after = Media_F2) %>%
  select(Genotipados, Media_F2, Desvio_F2, Media_F3, Desvio_F3) %>%
  gt() %>%
  tab_header(
    title = 'Pedirí 2',
    subtitle = '2071 individuos en total'
  ) %>%
  cols_label(
    Media_F2 = 'Media',
    Desvio_F2 = 'Desvío',
    Media_F3 = 'Media',
    Desvio_F3 = 'Desvío'
  ) %>%
  tab_row_group(
    label = 'Densidad 100.000',
    rows = 8:10
    )  %>%
  tab_row_group(
    label = 'Densidad 10.000',
    rows = 5:7
    ) %>%
  tab_row_group(
    label = 'Densidad 1.000',
    rows = 2:4
    ) %>%
  tab_row_group(
    label = 'Densidad 0',
    rows = 1
    ) %>%
  tab_spanner(
    label = 'F2',
    columns = c(2, 3)
  ) %>%
  tab_spanner(
    label = 'F3',
    columns = c(4, 5)
  )

Cor_F2_F3 %>%
  filter(Pedigrí == 'Pedigrí 3') %>%
  pivot_wider(names_from = Predicción, values_from = c(Media, Desvio)) %>%
  relocate(Desvio_F2, .after = Media_F2) %>%
  select(Genotipados, Media_F2, Desvio_F2, Media_F3, Desvio_F3) %>%
  gt() %>%
  tab_header(
    title = 'Pedirí 3',
    subtitle = '2091 individuos en total'
  ) %>%
  cols_label(
    Media_F2 = 'Media',
    Desvio_F2 = 'Desvío',
    Media_F3 = 'Media',
    Desvio_F3 = 'Desvío'
  ) %>%
  tab_row_group(
    label = 'Densidad 100.000',
    rows = 8:10
    )  %>%
  tab_row_group(
    label = 'Densidad 10.000',
    rows = 5:7
    ) %>%
  tab_row_group(
    label = 'Densidad 1.000',
    rows = 2:4
    ) %>%
  tab_row_group(
    label = 'Densidad 0',
    rows = 1
    ) %>%
  tab_spanner(
    label = 'F2',
    columns = c(2, 3)
  ) %>%
  tab_spanner(
    label = 'F3',
    columns = c(4, 5)
  )

Cor_F2_F3 %>%
  filter(Pedigrí == 'Pedigrí 4') %>%
  pivot_wider(names_from = Predicción, values_from = c(Media, Desvio)) %>%
  relocate(Desvio_F2, .after = Media_F2) %>%
  select(Genotipados, Media_F2, Desvio_F2, Media_F3, Desvio_F3) %>%
  gt() %>%
  tab_header(
    title = 'Pedirí 4',
    subtitle = '2131 individuos en total'
  ) %>%
  cols_label(
    Media_F2 = 'Media',
    Desvio_F2 = 'Desvío',
    Media_F3 = 'Media',
    Desvio_F3 = 'Desvío'
  ) %>%
  tab_row_group(
    label = 'Densidad 100.000',
    rows = 8:10
    )  %>%
  tab_row_group(
    label = 'Densidad 10.000',
    rows = 5:7
    ) %>%
  tab_row_group(
    label = 'Densidad 1.000',
    rows = 2:4
    ) %>%
  tab_row_group(
    label = 'Densidad 0',
    rows = 1
    ) %>%
  tab_spanner(
    label = 'F2',
    columns = c(2, 3)
  ) %>%
  tab_spanner(
    label = 'F3',
    columns = c(4, 5)
  )
```
